/**
 * GIVEN AN ARRAY, FIND THE SUM OF MAX SUBARRAY IN AN ARRAY. SUBARRAY SHOULD BE CONTINUOUS ELEMENTS
 * PICKED FROM THE ARRAY. 
 * EXAMPLE FOR ARRAY1=[1,2,3] THE POSSIBLE SUBARRAYS ARE [1], [2], [3], [1,2], [2,3], [1,2,3]
 * NOTE THAT [1,3] IS NOT CONTINUOUS SO IS NOT A SUBARRAY
 * NOTE THAT IF THE ARRAY2=[5,8,3] THE MAX SUM IS THE TOTAL SUM OF ALL NUMBER IS THE ARRAY
 * WHEN THE ELEMENTS ARE BOTH POSITIVE AND NEGATIVE, IT BECOMES TRICKY
 * EXAMPLE ARRAY3=[2,3,-8,7,-1,2,3] THE MAX POSSIBLE SUM IS 11 FROM SUM OF SUBARRAY3=[7,-1,2,3]
 * IF THE ARRAY IF MADE OF ONLY NEGATIVE NUMBERS, THE BIGGEST NUMBER IS THE MAX 
 * EXAMPLE FOR ARRAY4=[-6,-1,-8], [-1] IS IS THE MAX POSSIBLE SUBARRAY
 */

